version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  app:
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/your_database_name
    volumes:
      - .:/usr/src/app
